from .frame_window_calculator import NODE_CLASS_MAPPINGS as CALC_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as CALC_DISPLAY_MAPPINGS
from .video_frame_padder import NODE_CLASS_MAPPINGS as PADDER_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as PADDER_DISPLAY_MAPPINGS
from .pose_keypoint_smoother import NODE_CLASS_MAPPINGS as SMOOTHER_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as SMOOTHER_DISPLAY_MAPPINGS
from .video_seam_rife import NODE_CLASS_MAPPINGS as RIFE_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as RIFE_DISPLAY_MAPPINGS
from .qwen_camera_prompt import NODE_CLASS_MAPPINGS as QWEN_CAM_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as QWEN_CAM_DISPLAY_MAPPINGS
from .auto_switch import NODE_CLASS_MAPPINGS as AUTO_SWITCH_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as AUTO_SWITCH_DISPLAY_MAPPINGS
from .alpha_composite import NODE_CLASS_MAPPINGS as ALPHA_COMPOSITE_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as ALPHA_COMPOSITE_DISPLAY_MAPPINGS
from .llm_prompt_builder import NODE_CLASS_MAPPINGS as LLM_PROMPT_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as LLM_PROMPT_DISPLAY_MAPPINGS
from .video_resize import NODE_CLASS_MAPPINGS as VIDEO_RESIZE_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_RESIZE_DISPLAY_MAPPINGS
from .nano_banana_batch import NODE_CLASS_MAPPINGS as NANO_BANANA_BATCH_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as NANO_BANANA_BATCH_DISPLAY_MAPPINGS
from .video_batch_loader import NODE_CLASS_MAPPINGS as VIDEO_BATCH_LOADER_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as VIDEO_BATCH_LOADER_DISPLAY_MAPPINGS
from .filename_formatter import NODE_CLASS_MAPPINGS as FILENAME_FORMATTER_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as FILENAME_FORMATTER_DISPLAY_MAPPINGS

WEB_DIRECTORY = "web"

NODE_CLASS_MAPPINGS = {**CALC_MAPPINGS, **PADDER_MAPPINGS, **SMOOTHER_MAPPINGS, **RIFE_MAPPINGS, **QWEN_CAM_MAPPINGS, **AUTO_SWITCH_MAPPINGS, **ALPHA_COMPOSITE_MAPPINGS, **LLM_PROMPT_MAPPINGS, **VIDEO_RESIZE_MAPPINGS, **NANO_BANANA_BATCH_MAPPINGS, **VIDEO_BATCH_LOADER_MAPPINGS, **FILENAME_FORMATTER_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**CALC_DISPLAY_MAPPINGS, **PADDER_DISPLAY_MAPPINGS, **SMOOTHER_DISPLAY_MAPPINGS, **RIFE_DISPLAY_MAPPINGS, **QWEN_CAM_DISPLAY_MAPPINGS, **AUTO_SWITCH_DISPLAY_MAPPINGS, **ALPHA_COMPOSITE_DISPLAY_MAPPINGS, **LLM_PROMPT_DISPLAY_MAPPINGS, **VIDEO_RESIZE_DISPLAY_MAPPINGS, **NANO_BANANA_BATCH_DISPLAY_MAPPINGS, **VIDEO_BATCH_LOADER_DISPLAY_MAPPINGS, **FILENAME_FORMATTER_DISPLAY_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
