from .frame_window_calculator import NODE_CLASS_MAPPINGS as CALC_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as CALC_DISPLAY_MAPPINGS
from .video_frame_padder import NODE_CLASS_MAPPINGS as PADDER_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as PADDER_DISPLAY_MAPPINGS
from .pose_keypoint_smoother import NODE_CLASS_MAPPINGS as SMOOTHER_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as SMOOTHER_DISPLAY_MAPPINGS
from .video_seam_rife import NODE_CLASS_MAPPINGS as RIFE_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as RIFE_DISPLAY_MAPPINGS
from .qwen_camera_prompt import NODE_CLASS_MAPPINGS as QWEN_CAM_MAPPINGS, \
    NODE_DISPLAY_NAME_MAPPINGS as QWEN_CAM_DISPLAY_MAPPINGS

WEB_DIRECTORY = "web"

NODE_CLASS_MAPPINGS = {**CALC_MAPPINGS, **PADDER_MAPPINGS, **SMOOTHER_MAPPINGS, **RIFE_MAPPINGS, **QWEN_CAM_MAPPINGS}
NODE_DISPLAY_NAME_MAPPINGS = {**CALC_DISPLAY_MAPPINGS, **PADDER_DISPLAY_MAPPINGS, **SMOOTHER_DISPLAY_MAPPINGS, **RIFE_DISPLAY_MAPPINGS, **QWEN_CAM_DISPLAY_MAPPINGS}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS", "WEB_DIRECTORY"]
